name: 'Deploy to AWS S3'
description: 'Deploy a statis website to an AWS S3 bucket.'
inputs:
  bucket:
    description: 'The name of the S3 bucket to deploy to.'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket.'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder to deploy to the S3 bucket.'
    required: true
runs:
  using: 'node16'     #usando node como runtime
  main: 'main.js'  #usando deploy.js como main, que é o script que será executado para fazer o deploy através desta action
