name: 'Get & Cache Dependencies'
##em actions não se usa 'on'
description: 'Get the dependencies (via npm) and cache them.'
inputs:
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true' #se o cache não foi atingido ou se não for para usar cache
      run: npm ci
      shell: bash     #usando bash como shell
